//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philane.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeesAnswer
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public int QuestionId { get; set; }
        public Nullable<bool> Yes { get; set; }
        public Nullable<bool> No { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Question Question { get; set; }
    }
}
